### ISSUE TITLE
モジュール単位でnpmパッケージに分ける & モノリポにする

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/slacc#2]
今後もモジュールを追加していくなら、slacc coreと各モジュールを分離する（かつモノリポ管理にする）みたいなことをする必要がありそう

**Comment by acid-chicken** [comment]
パッケージに分ける必要は感じておらずむしろここにロジックを可能な限り書かない方向にしたい（ロジックは分離してスタンドアロンなライブラリにすべき）

**Comment by acid-chicken** [comment]
![image](https://user-images.githubusercontent.com/20679825/235309707-4cbf0be3-b72e-43ca-9ac2-ff818ecfb3c5.png)

**Comment by acid-chicken** [comment]
じゃないと npm パッケージを 3 桁個管理することになるが

**Comment by tamaina** [comment]
> npm パッケージを 3 桁個管理する

それでよくね派

**Comment by acid-chicken** [comment]
得られるメリットがない

**Comment by tamaina** [comment]
> 得られるメリット

Misskey外で使う時余計なバイナリを引っ張ってこなくて済む  
(まあMisskey内で使う前提だろというのはうん)

**Comment by acid-chicken** [comment]
Misskey 外で使うことを想定するつもりは毛頭ないし、繰り返すけどバインディングで留めるから使うならスタンドアロンのライブラリ使えになるが

**Comment by acid-chicken** [comment]
なぜロジックをここに書くべきでないかはこの図を見て理解してほしい ![image](https://user-images.githubusercontent.com/20679825/235355794-76f13e9f-d360-4700-b977-b823842e4d53.png)

**Comment by tamaina** [comment]
binding周りが全部自作だと勘違いしてた（napiというものがあるのか）
